global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'fastify-api'
    static_configs:
      - targets: ['fastify-api:8080']
    metrics_path: /metrics
    scheme: http